name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Check format
        run: poetry run task format_check
      - name: Lint code
        run: poetry run task ruff_lint --output-format=github
      - name: Check types
        run: poetry run task mypy
