name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Check isort
        run: poetry run task isort_check
      - name: Check black
        run: poetry run task black_check
      - name: Check mypy
        run: poetry run task mypy
