name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install dependencies
        run: poetry install --only main,test
      - name: Run tests
        run: poetry run pytest tests --junitxml=junit.xml -n auto
      - name: Test reporter
        uses: phoenix-actions/test-reporting@v12
        if: success() || failure()
        with:
          name: Secret Santa tests on ${{ matrix.os }} (Python ${{ matrix.python-version }}) Report
          path: junit.xml
          reporter: java-junit
          output-to: step-summary
